### ISSUE TITLE
Connecting to a remote DB and auth

### ISSUE THREAD

**Issue by lc5415** [jupyter-xeus/xeus-sqlite#100]
Hi! I've always wanted a Jupiter SQL and this one seems great! I was wondering how can one connect to a remote DB and how authentication should be handled. I haven't seen anything related to this in the docs 

Thank you so much for your work!

**Comment by marimeireles** [comment]
Hey @lc5415 sorry for the late reply. So, what kind of SQL do you want to use?
This project only supports SQLite and I'm not sure SQLite offers the possibility of connecting to a remote DB? Sorry, I just know the API from CppSQLite, I'm not very knowledgeable in the DB specifics.

If you're interested in using a different SQL backend, like MySQL or Postgresql [...] I'm developing a more complete version of this kernel called xeus-soci, based on the SOCI project.
You can check my progress here: https://github.com/jupyter-xeus/xeus-soci
It's near ready and I intend to have a first 0.0.1 version by the end of this week :)

**Comment by lc5415** [comment]
Hi @marimeireles thanks for your reply. I intend to use notebooks at work where I use hive and presto. I am by no means a DB expert so I wouldn't know what SQLite supports. Do you think you think the SOCI project would support hive and presto connections? 

If it helps I usually connect to these DBs using python's `pyhive`, there may be something in there that could help figure out what's needed to connect to a Hive DB.

**Comment by lc5415** [comment]
Also @marimeireles, I cannot access this link [https://github.com/jupyter-xeus/xeus-soci](https://github.com/jupyter-xeus/xeus-soci), the repository might be private.

**Comment by marimeireles** [comment]
Hey @lc5415, turns out it was a private repo, sorry, forgot about that. Now you should have access to it, it's a very early version most stuff on the README doesn't exist yet and you'd have to build everything from source.

SOCI supports ODBC so if there are ODBC drivers for Presto or Hive you could use that to connect. If not, then you would have to add support for Presto directly in SOCI.
