### ISSUE TITLE
Missing library

### ISSUE THREAD

**Issue by Epithumia** [jupyter-xeus/xeus-sqlite#108]
When installing xeus-sqlite inside jupyterlab (TLJH, to be accurate), it fails to install a required library, and while the kernel shows up in the list, it will not connect to it. User logs showed the issue:

```
/opt/tljh/user/bin/xsqlite: error while loading shared libraries: libxvega.so.0: cannot open shared object file: No such file or directory
```

Running ldd on it confirmed the issue.

This was fixed by manually installing xvega

**Comment by marimeireles** [comment]
Huh, how did you install xeus-sqlite?
The package by conda forge contains the requirement for `xvega` https://github.com/conda-forge/xeus-sqlite-feedstock/blob/c670b03a073c209d923ddec0a70f2a4dd0d310bf/recipe/meta.yaml#L30
And this is the only "officially supported" way of installing the package, but if you have a different approach and would like to add it to the readme, it'll be very appreciated.

**Comment by Epithumia** [comment]
```
conda install xeus-sqlite -c conda-forge
```

Neither xvega nor xvega-bindings were installed.

**Comment by marimeireles** [comment]
Oh, wow, I never realized that before.
I'm on it, created a new version for the recipe, it should take a few hours to reflect the change tho... Cause I'm not seeing it immediately. Will test again in 3h or so.

**Comment by marimeireles** [comment]
Fixed. Thank you.
