### ISSUE TITLE
%CREATE instantly kills the kernel

### ISSUE THREAD

**Issue by Epithumia** [jupyter-xeus/xeus-sqlite#109]
As the title says.

Tested on my install:
```
%CREATE "testdb.db"
```
results in "The kernel appears to have died. It will restart automatically." (and it doesn't, in fact). User log only shows the kernel restarting, but not what caused it to die.

Same thing happens with the example notebook ('Simple Operations').

Edit : once again, the documentation is wrong. %CREATE takes two arguments, but both doc and examples only pass one, which immediately kills the kernel.

In the example notebook, this command works fine:
```
%CREATE potato.db potato
```

**Comment by marimeireles** [comment]
Maybe it's the same problem with the `"`?
Also, you're not giving a name to your DB in the first example, might be that.
Anyways, it seems like we have a problem with outdated docs here...

**Comment by Epithumia** [comment]
It kills the server all the same with double quotes. 

Anyway, there are two issues here:
- neither the documentation nor the examples (the 'Simple Operations' notebook crashes the kernel too) are up-to-date with the code.
- the missing parameter should be handled gracefully with an error message, instead of killing the kernel.

**Comment by marimeireles** [comment]
Agreed, I thought I was handling it, but apparently not. Thanks for summarizing it clearly :)
I can't take care of it right now, unfortunately, but it's good to keep track!

**Comment by marimeireles** [comment]
Fixed by https://github.com/jupyter-xeus/xeus-sqlite/pull/116
