### ISSUE TITLE
%LOAD magic + doc

### ISSUE THREAD

**Issue by Epithumia** [jupyter-xeus/xeus-sqlite#110]
The %LOAD magic command doesn't behave like documented.

For example, this works fine (with testdb.db existing in the same folder as the notebook): 
```
%LOAD testdb.db
```
Giving it an absolute/relative path works as well 
```
%LOAD /absolute/path/to/testdb.db
```

On the other hand, this doesn't work:
```
%LOAD "testdb.db"
```
Result: "Error: The path doesn't exist." Same issue with single quotes, with absolute or relative paths.

**Comment by marimeireles** [comment]
huh, thank you for capturing this!
Feel free to open a PR to change it :)

**Comment by marimeireles** [comment]
This is fixed by https://github.com/jupyter-xeus/xeus-sqlite/pull/116
