### ISSUE TITLE
Needs fix for xeus 2.0.0

### ISSUE THREAD

**Issue by Schamschula** [jupyter-xeus/xeus-sqlite#112]
While rebuilding xeus-sqlite 0.3.0 against xeus 2.0.0, I get the following errors:

> [ 87%] Building CXX object CMakeFiles/xsqlite.dir/src/main.cpp.o
> /usr/bin/clang++ -DGUID_CFUUID -DJSON_DIAGNOSTICS=0 -DJSON_USE_IMPLICIT_CONVERSIONS=1 -DSQLITE_DEBUG=1 -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_ENABLE_EXPLAIN_COMMENTS=1 -DSQLITE_MEMDEBUG=1 -DXEUS_SQLITE_EXPORTS -DXVEGA_EXPORTS -Dxsqlite_EXPORTS -I/opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_databases_xeus-sqlite/xeus-sqlite/work/xeus-sqlite-0.3.0/include -isystem /opt/local/include -isystem /opt/local/include/openssl -pipe -Os -DNDEBUG -I/opt/local/include -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -O3 -DNDEBUG -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.14 -Wunused-parameter -Wextra -Wreorder -mtune=generic -march=native -std=gnu++17 -MD -MT CMakeFiles/xsqlite.dir/src/main.cpp.o -MF CMakeFiles/xsqlite.dir/src/main.cpp.o.d -o CMakeFiles/xsqlite.dir/src/main.cpp.o -c /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_databases_xeus-sqlite/xeus-sqlite/work/xeus-sqlite-0.3.0/src/main.cpp
> /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_databases_xeus-sqlite/xeus-sqlite/work/xeus-sqlite-0.3.0/src/main.cpp:62:36: error: no member named 'make_xserver_shell_main' in namespace 'xeus'
>                              xeus::make_xserver_shell_main);
>                              ~~~~~~^
> /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_databases_xeus-sqlite/xeus-sqlite/work/xeus-sqlite-0.3.0/src/main.cpp:78:36: error: no member named 'make_xserver_shell_main' in namespace 'xeus'
>                              xeus::make_xserver_shell_main);
>                              ~~~~~~^
> 2 errors generated.
>

**Comment by marimeireles** [comment]
Hey @Schamschula thanks for reporting, Johan and I are having a look for the `sql` kernel and should be a similar process for the `sqlite` https://github.com/jupyter-xeus/xeus-sql/pull/47. I'll keep you posted =)
Or if you want to contribute, you're very welcome! I'm around if you have any questions.

**Comment by marimeireles** [comment]
Johan pushed a PR fixing it :)
Soon we will have a new version out on conda-forge, but must be working now from master.
If not, feel free to reopen this issue.
Thank you.

**Comment by Schamschula** [comment]
Works for me.

Thanks!
