### ISSUE TITLE
Add Vega examples to docs

### ISSUE THREAD

**Issue by bbkane** [jupyter-xeus/xeus-sqlite#123]
Hello,

I'm new to Vega and xeus, so I went to the [docs](https://xeus-sqlite.readthedocs.io/en/latest/) to look for examples of creating charts, like how to make a line chart, histogram, etc. I didn't see any. Would someone more familiar with the project mind adding some or pointing me to any I missed?

**Comment by marimeireles** [comment]
Hi @bbkane, sorry I missed this.
Currently our docs aren't really covering that, but you can check this [binder](https://mybinder.org/v2/gh/jupyter-xeus/xeus-sqlite/stable?filepath=examples/Simple%20operations.ipynb) link that should give you an idea on what's possible.
Additional docs can be found in the [vega](https://vega.github.io/vega-lite/docs/) website.

If you have the time and the interest of contributing docs for these graphs it'd be amazing!

Any other questions you might have, I'm around to answer :)

**Comment by marimeireles** [comment]
Oops! Sorry about that, you're right.
So this is where you'll find examples on what commands to use to render the graphs, there are two possibilities:
1. use the xvega language that I developed and it's incomplete
2. use the json variant that's documented in xvega-lite website
If you check this binder link you'll find an example for 1 [here](https://hub.gke2.mybinder.org/user/jupyter-xeus-xeus-sql-25duexc6/lab/tree/examples/SQLite.ipynb) and 2 [here](https://hub.gke2.mybinder.org/user/jupyter-xeus-xeus-sql-25duexc6/lab/tree/examples/XVega%20operations.ipynb).

**Comment by bbkane** [comment]
Neither of those links open:

<img width="732" alt="image" src="https://user-images.githubusercontent.com/6081085/163318539-e2f315e0-ac90-4fef-98a5-ba3d2689e48e.png">

No worries; have a great day.
