### ISSUE TITLE
xeus-sqlite fails to compile with 'cpp-tabulate >=1.3,<2'

### ISSUE THREAD

**Issue by kathoef** [jupyter-xeus/xeus-sqlite#129]
While the [install from source command](https://github.com/jupyter-xeus/xeus-sqlite/tree/b0838a3444a79a5258d4ecda761fa426a52c80c3#installing-from-source) probably works because it hard codes `cpp-tabulate=1.3`, the [dependency table](https://github.com/jupyter-xeus/xeus-sqlite/tree/b0838a3444a79a5258d4ecda761fa426a52c80c3#dependencies) is a bit misleading. I found this out, because the current `xeus-sqlite` conda-forge package seems to be broken and I attempted to compile `xeus-sqlite` myself. For details see: https://github.com/conda-forge/xeus-sqlite-feedstock/issues/20 (Sorry for cross-posting!)

**Comment by JohanMabille** [comment]
>  (Sorry for cross-posting!)

No worries, thanks for investigating this!
