### ISSUE TITLE
No lexer found for language sqlite

### ISSUE THREAD

**Issue by martinRenou** [jupyter-xeus/xeus-sqlite#21]
When running xsqlite from Jupyter console `jupyter console --kernel=xsqlite`, I get a
```
/home/martin/miniconda3/envs/xeus-sqlite/lib/python3.8/site-packages/jupyter_console/ptshell.py:98: UserWarning: No lexer found for language 'sqlite'. Treating as plain text.
```

I wonder if this is just about changing the language name to something that is recognized by Jupyter console, or if there is a way to add sqlite support in jupyter console (or even just discard the warning)

**Comment by SylvainCorlay** [comment]
Pygments know `sqlite3`.

https://pygments.org/docs/lexers/#pygments.lexers.sql.SqliteConsoleLexer

It also has a generic 'sql' language.

Whatever we choose should also work for codemirror.

**Comment by marimeireles** [comment]
Hum.. And where do I change this lexer option?
I looked a bit in the internet and in other kernels we have but couldn't find it.

**Comment by SylvainCorlay** [comment]
@marimeireles I am not sure but you may want to check if it works when changing the language in the kernel info reply.
