### ISSUE TITLE
Kernel dies in Binder demo

### ISSUE THREAD

**Issue by simonw** [jupyter-xeus/xeus-sqlite#49]
I'm getting the error "The kernel appears to have died. It will restart automatically." consistently in the Binder demo.

<img width="1179" alt="Trying_this_out_-_Jupyter_Notebook" src="https://user-images.githubusercontent.com/9599/84420720-4b696600-abcf-11ea-89b1-b3662dc82d33.png">

Steps to reproduce:

1. Launch this: https://mybinder.org/v2/gh/jupyter-xeus/xeus-sqlite/stable
2. Create new xsqlite notebook.
3. Run `select * from sqlite_master`

**Comment by simonw** [comment]
It looks like it's producing a core dump each time this happens:

<img width="1204" alt="Home_Page_-_Select_or_create_a_notebook" src="https://user-images.githubusercontent.com/9599/84420835-79e74100-abcf-11ea-98af-e5bb27e929cc.png">

I've uploaded the most recent core dump (44MB) here in case it's useful for investigating this: https://static.simonwillison.net/static/2020/core.xsqlite.95.1591896878

**Comment by martinRenou** [comment]
I suppose it's the same issue as here: https://github.com/jupyter-xeus/xeus-sqlite/issues/17. The problem occurs when no database was loaded. You need to load a database before doing any selection.

You can look at the example notebook to see how to load a Database. Anyway let's keep this issue opened until this is properly fixed. We should show an error message when no database is loaded, instead of letting the kernel die.

**Comment by marimeireles** [comment]
Yeah, @martinRenou is right.

Sorry for that, thought I had fixed in previous versions and forgot to reopen the issue. Will do it now.

Thanks for the heads up @simonw!

**Comment by simonw** [comment]
Is there a mechanism to load a `:memory:` database? Could that even be the default if no database has been loaded?

**Comment by simonw** [comment]
Hooray got it working!

<img width="1163" alt="Untitled_-_Jupyter_Notebook" src="https://user-images.githubusercontent.com/9599/84431723-9cce2100-abe0-11ea-81c2-39eb43f8964f.png">

**Comment by martinRenou** [comment]
@simonw I see you don't have syntax highlighting, can I ask you which Jupyter client (Jupyter Notebook, JupyterLab, colab) you are using?

**Comment by simonw** [comment]
That was the Binder demo running in Firefox on macOS.

**Comment by martinRenou** [comment]
Thanks. That is odd. It should work in Jupyter Notebook. I just tried the Binder link on Firefox and it works.

**Comment by marimeireles** [comment]
Yeah it works for me too. Just tested on a Firefox.
I don't understand this syntax highlighting thing.

**Comment by martinRenou** [comment]
Yeah it's odd.

@simonw Where does this `:memory:` comes from? Do you think we should support it? `%CREATE test.db` actually creates a file so it's not exactly what you were suggesting I guess. I like the idea of having a full in-memory database, that you can save to disk later on or not.

**Comment by SylvainCorlay** [comment]
Closing as answered. We can open a separate issue about supporting in-memory databases.
