### ISSUE TITLE
typo in CMakefiles

### ISSUE THREAD

**Issue by joequant** [jupyter-xeus/xeus-sqlite#56]
Seems to be a typo in the file

diff --git a/CMakeLists.txt b/CMakeLists.txt
index 6c1d12a..8c6282f 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -34,7 +34,7 @@ foreach(ver ${xsqlite_version_defines})
     endif()
 endforeach()
 set(${PROJECT_NAME}_VERSION
-${XSQLITE_VERSION_MAJOR}.${XPYT_VERSION_MINOR}.${XPYT_VERSION_PATCH})
+${XSQLITE_VERSION_MAJOR}.${XSQLITE_VERSION_MINOR}.${XSQLITE_VERSION_PATCH})
 message(STATUS "Building xeus-sqlite v${${PROJECT_NAME}_VERSION}")

**Comment by joequant** [comment]
Addressed by #57 which also puts in a fix for a minor version grab problem

**Comment by marimeireles** [comment]
Problem fixed on #57 . Thank you @joequant!
