### ISSUE TITLE
Text don't appear with typing on the console  when using jupyter console 

### ISSUE THREAD

**Issue by avinal** [jupyter-xeus/xeus-sqlite#87]
## Problem
When the kernel is loaded using in jupyter console the commands don't appear on the terminal 
![image](https://user-images.githubusercontent.com/74113200/98927857-11deb300-24ff-11eb-8969-e34288804147.png)

## what is working
* Commands get executed and results still appear
* Working fine in the browser

## how to reproduce
* `jupyter console --kernel xsqlite`
* type commands

**Comment by marimeireles** [comment]
Thanks for posting @avinal, I'm kinda clueless on what's going on here. Will keep tinkering.

**Comment by marimeireles** [comment]
So! A contributor to a project that's a fork to this one found the answer! :)
It's in the following PR https://github.com/jupyter-xeus/xeus-sql/pull/24. All one needs to do is to map the changes from there to here and it should work fine!

**Comment by marimeireles** [comment]
Fixed by https://github.com/jupyter-xeus/xeus-sqlite/pull/116
